Repository nextcloud-libraries/eslint-config, pull requests merged in 2022-01, with the labels that each got.

#266 Eslint 8
  index.js
  package-lock.json
  package.json
Labels: dependencies

#267 v7.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, dependencies

#270 Allow component names to be single-word
  index.js
Labels: bug

#272 Fix usual same-line vue attribute behaviour
  index.js
Labels: bug

#276 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#281 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies
