Repository nextcloud-libraries/eslint-config, pull requests merged in 2023-06, with the labels that each got.

#548 chore: update workflows from templates
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node.yml
  .github/workflows/npm-publish.yml
Labels: dependencies, automated, 3. to review

#562 Support Composition API & Typescript + Vue projects
  CHANGELOG.md
  README.md
  index.js
  package-lock.json
  package.json
  parts/base.js
  parts/typescript.js
  parts/vue.js
  tests/eslint-config.test.ts
  tests/eslint-typescript-config.test.ts
  tests/fixtures/composition-test.vue
  tests/fixtures/typescript-test.vue
  typescript.js
Labels: enhancement, 3. to review

#563 chore: update node engines to next LTS
  package.json
Labels: dependencies, automated, 3. to review

#567 fix: Add Typescript overrides for all valid Typescript file extensions
  parts/typescript.js
Labels: 3. to review

#568 v8.3.0-beta.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#569 chore: update typescript deps and co
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug, dependencies, 3. to review

#570 fix: allow empty functions
  CHANGELOG.md
  parts/typescript.js
Labels: 3. to review

#572 Make eslint to take this config for linting the config
  package.json
  parts/base.js
  parts/typescript.js
  parts/vue.js
Labels: 3. to review

#571 fix(typescript): Allow generic type parameters on function calls
  parts/typescript.js
Labels: 3. to review
