Repository nextcloud-libraries/eslint-config, pull requests merged in 2024-05, with the labels that each got.

#766 feat: Add `vue3` sub-configuration to allow linting Vue 3 projects
  README.md
  parts/vue3.js
  vue3.js
Labels: enhancement, 3. to review

#768 chore: Prepare 8.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#771 fix(vue3): align rules with Vue 2 rules
  parts/vue3.js
Labels: bug, 3. to review

#770 fix(vue3): config crashes ESLint
  parts/vue3.js
Labels: bug, 3. to review

#772 release: v8.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
