Repository nextcloud-libraries/eslint-config, pull requests merged in 2025-07, with the labels that each got.

#1096 fix: ignore test report directories from linting
  lib/configs/filesystem.ts
Labels: bug, 3. to review

#1097 fix(vue): also ignore the global router link component
  lib/configs/vue.ts
Labels: bug, 3. to review

#1084 fix(no-deprecated-props): respect nextcloud/vue library version for the rule
  lib/plugins/nextcloud-vue/rules/no-deprecated-exports.test.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-exports.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-props.test.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-props.ts
Labels: bug, 3. to review

#1108 feat(filesystem): ignore all files within the `.gitignore`
  lib/configs/filesystem.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#1112 fix(l10n-plugin): also check translation strings in `n` method
  lib/plugins/l10n/rules/enforce-ellipsis.test.ts
  lib/plugins/l10n/rules/enforce-ellipsis.ts
Labels: bug, 3. to review

#1113 feat(l10n-plugin): also handle vue templates
  lib/configs/vue.ts
  lib/plugins/l10n/index.ts
  lib/plugins/l10n/rules/enforce-ellipsis-vue.test.ts
  lib/plugins/l10n/rules/enforce-ellipsis-vue.ts
  lib/plugins/l10n/rules/enforce-ellipsis.ts
  lib/plugins/l10n/rules/index.ts
  lib/plugins/l10n/rules/non-breaking-space-vue.test.ts
  lib/plugins/l10n/rules/non-breaking-space-vue.ts
  lib/plugins/l10n/rules/non-breaking-space.test.ts
  lib/plugins/l10n/rules/non-breaking-space.ts
Labels: enhancement, 3. to review

#1115 chore: prepare v9.0.0-rc.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
