Repository nextcloud-libraries/eslint-config, pull requests merged in 2025-05, with the labels that each got.

#1033 feat(codeStyle): enforce top-level-function
  lib/configs/codeStyle.ts
  package-lock.json
  package.json
  tests/config-codestyle.test.ts
  tests/config-javascript.test.ts
  tests/fixtures/codestyle/input/arrow-function.ts
  tests/fixtures/codestyle/input/function.ts
  tests/fixtures/codestyle/output/arrow-function.ts
  tests/fixtures/codestyle/output/function.ts
Labels: enhancement, 3. to review

#995 fix(documentation): do not remove JSDoc types in Vue JS files
  lib/configs/documentation.ts
  tests/config-typescript.test.ts
  tests/fixtures/JsdocJavascriptWithTypes.vue
  tests/fixtures/JsdocJavascriptWithoutTypes.vue
  tests/fixtures/JsdocTypescriptWithTypes.vue
  tests/fixtures/JsdocTypescriptWithoutTypes.vue
  tests/fixtures/typescript-vue-overrides.vue
Labels: bug

#1046 test: fix tests and add workflow to run them on CI
  .github/workflows/node-test.yml
  tests/fixtures/JsdocJavascriptWithTypes.vue
  tests/fixtures/JsdocJavascriptWithoutTypes.vue
  tests/fixtures/JsdocTypescriptWithTypes.vue
  tests/fixtures/JsdocTypescriptWithoutTypes.vue
Labels: 3. to review
