Repository nextcloud-libraries/eslint-config, pull requests merged in 2025-06, with the labels that each got.

#1009 docs: add documentation about update policy and development
  README.md
Labels: 3. to review

#1061 fix: ignore `l10n` and `js` directory for apps
  lib/configs/filesystem.ts
Labels: bug, 3. to review

#1064 feat(vue3): add script-setup releated rules
  lib/configs/vue.ts
  lib/configs/vue3.ts
Labels: enhancement, 3. to review

#1066 chore: add active node version (24) to supported engines
  package.json
Labels: 3. to review

#1067 build: add common changelog formatting and documentation for it
  CHANGELOG.md
  README.md
  build/format-changelog.mjs
  package.json
Labels: 3. to review

#1068 chore: prepare v9.0.0-rc.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#1069 fix(no-deprecated-props): extend existing rules to support other components
  lib/plugins/nextcloud-vue/rules/no-deprecated-props.test.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-props.ts
Labels: enhancement, 3. to review
