Repository nextcloud-libraries/eslint-config, pull requests merged in 2025-04, with the labels that each got.

#970 fix(javascript): allow using functions before they are defined
  lib/configs/javascript.ts
  tests/config-javascript.test.ts
Labels: bug, 3. to review

#967 chore: do not bundle config but just use Typescript
  eslint.config.js
  lib/configs/codeStyle.ts
  lib/configs/documentation.ts
  lib/configs/javascript.ts
  lib/configs/json.ts
  lib/configs/node.ts
  lib/configs/typescript.ts
  lib/configs/vue.ts
  lib/configs/vue2.ts
  lib/configs/vue3.ts
  lib/index.ts
  lib/plugins/l10n/index.ts
  lib/plugins/l10n/rules/enforce-ellipsis.test.ts
  lib/plugins/l10n/rules/non-breaking-space.test.ts
  lib/plugins/nextcloud/index.ts
  lib/plugins/nextcloud/plugin.d.ts
  lib/plugins/nextcloud/rules/no-deprecations.test.ts
  lib/plugins/nextcloud/rules/no-deprecations.ts
  lib/plugins/nextcloud/rules/no-removed-apis.test.ts
  lib/plugins/nextcloud/rules/no-removed-apis.ts
  lib/plugins/nextcloud/utils/version-parser.test.ts
  lib/plugins/nextcloud/utils/version-parser.ts
  lib/plugins/packageJson.ts
  lib/version.ts
  package-lock.json
  package.json
  tests/tsconfig.json
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: 3. to review

#971 refactor: use camelCase for internal variables
  lib/plugins/l10n/index.ts
  lib/plugins/nextcloud/index.ts
  lib/plugins/packageJson.ts
  lib/version.ts
Labels: 3. to review

#972 fix(javascript): add missing `appName` and `appVersion` global + fix access
  lib/configs/javascript.ts
Labels: bug, 3. to review

#974 fix(globs): properly ignore test files
  lib/globs.ts
Labels: bug, 3. to review

#975 chore: allow to run `npm lint` without compile step
  eslint.config.ts
  lib/configs/documentation.ts
  lib/plugins/nextcloud/rules/no-removed-apis.ts
  package.json
  tsconfig.json
Labels: 3. to review

#977 fix(typescript): enforce `import type` for type only imports
  lib/configs/filesystem.ts
  lib/configs/typescript.ts
  lib/plugins/nextcloud/index.ts
  tests/setup.ts
Labels: bug, 3. to review

#982 fix: require node ^20.19
  package.json
Labels: bug, 3. to review

#998 fix(vue): allow JS Vue files
  lib/configs/vue.ts
Labels: bug

#981 feat: add import and export rules
  lib/configs/codeStyle.ts
  lib/configs/documentation.ts
  lib/configs/imports.ts
  lib/configs/javascript.ts
  lib/configs/json.ts
  lib/configs/node.ts
  lib/configs/typescript.ts
  lib/configs/vue.ts
  lib/configs/vue2.ts
  lib/configs/vue3.ts
  lib/index.ts
  lib/plugins/l10n/rules/enforce-ellipsis.test.ts
  lib/plugins/l10n/rules/non-breaking-space.test.ts
  lib/plugins/nextcloud/index.ts
  lib/plugins/nextcloud/rules/index.ts
  lib/plugins/nextcloud/rules/no-deprecations.test.ts
  lib/plugins/nextcloud/rules/no-removed-apis.test.ts
  lib/plugins/nextcloud/rules/no-removed-apis.ts
  lib/plugins/nextcloud/utils/version-parser.test.ts
  lib/plugins/nextcloud/utils/version-parser.ts
  lib/plugins/packageJson.ts
  package-lock.json
  package.json
  tests/config-codestyle.test.ts
  tests/config-javascript.test.ts
  tests/config-typescript.test.ts
  tests/fixtures/codestyle/input/exports.ts
  tests/fixtures/codestyle/input/imports.ts
  tests/fixtures/codestyle/output/exports.ts
  tests/fixtures/codestyle/output/imports.ts
  tests/setup.ts
Labels: enhancement, 3. to review

#939 feat: introduce @nextcloud/vue eslint plugin
  lib/configs/vue.ts
  lib/plugins/nextcloud-vue/index.ts
  lib/plugins/nextcloud-vue/rules/index.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-exports.test.ts
  lib/plugins/nextcloud-vue/rules/no-deprecated-exports.ts
  lib/plugins/nextcloud-vue/utils/lib-version-parser.test.ts
  lib/plugins/nextcloud-vue/utils/lib-version-parser.ts
Labels: enhancement, 3. to review

#1010 chore: prepare v9.0.0-rc.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
